apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tconfigd-service-account-binding
subjects:
  - kind: ServiceAccount
    name: tconfigd-service-account
    namespace: tratteria-system
roleRef:
  kind: ClusterRole
  name: tconfigd-service-account-role
  apiGroup: rbac.authorization.k8s.io
