apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tokenetesconfigs.tokenetes.io
spec:
  group: tokenetes.io
  names:
    kind: TokenetesConfig
    plural: tokenetesconfigs
    singular: tokenetesconfig
    listKind: TokenetesConfigList
    shortNames:
      - tokenetescfg
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                token:
                  type: object
                  properties:
                    issuer:
                      type: string
                      description: "URL of the token issuer."
                    audience:
                      type: string
                      description: "URL of the token audience."
                    lifeTime:
                      type: string
                      description: "Lifetime of the token."
                subjectTokens:
                  type: object
                  properties:
                    OIDC:
                      type: object
                      properties:
                        clientId:
                          type: string
                        providerURL:
                          type: string
                        subjectField:
                          type: string
                    selfSigned:
                      type: object
                      properties:
                        validation:
                          type: boolean
                        jwksEndpoint:
                          type: string
                accessEvaluationAPI:
                  type: object
                  properties:
                    enableAccessEvaluation:
                      type: boolean
                      description: "Toggle to enable or disable access evaluation."
                    endpoint:
                      type: string
                    authentication:
                      type: object
                      properties:
                        method:
                          type: string
                        token:
                          type: object
                          properties:
                            value:
                              type: string
                tokenGenerationAuthorizedServiceIds:
                  type: array
                  items:
                    type: string
            status:
              type: object
              properties:
                verificationApplied:
                  type: boolean
                generationApplied:
                  type: boolean
                status:
                  type: string
                  default: "PENDING"
                lastErrorMessage:
                  type: string
                  nullable: true
                retries:
                  type: integer
                  default: 0
      additionalPrinterColumns:
        - name: "Status"
          type: "string"
          jsonPath: ".status.status"
          description: "Current status of the tokenetesConfig."
        - name: "Age"
          type: "date"
          jsonPath: ".metadata.creationTimestamp"
          description: "Time since creation"
        - name: "Retries"
          type: "integer"
          jsonPath: ".status.retries"
          description: "Number of retries attempted."
      subresources:
        status: {}
